// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSnmprUEUMFywSArFfHfB65dWzzAF1Ug',
    appId: '1:11209352050:web:90837b3779fe05b63973eb',
    messagingSenderId: '11209352050',
    projectId: 'auto-attendance-webapp',
    authDomain: 'auto-attendance-webapp.firebaseapp.com',
    storageBucket: 'auto-attendance-webapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHVGirALJk4Xa3fyXANj8TyIwRR-UmkDY',
    appId: '1:11209352050:android:ddb55444329015403973eb',
    messagingSenderId: '11209352050',
    projectId: 'auto-attendance-webapp',
    storageBucket: 'auto-attendance-webapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFRnvk8J-e3EijzQfu-GdS9flJ-tvIC98',
    appId: '1:11209352050:ios:d9a4bc0fbc4f60663973eb',
    messagingSenderId: '11209352050',
    projectId: 'auto-attendance-webapp',
    storageBucket: 'auto-attendance-webapp.firebasestorage.app',
    iosBundleId: 'com.example.autoAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFRnvk8J-e3EijzQfu-GdS9flJ-tvIC98',
    appId: '1:11209352050:ios:d9a4bc0fbc4f60663973eb',
    messagingSenderId: '11209352050',
    projectId: 'auto-attendance-webapp',
    storageBucket: 'auto-attendance-webapp.firebasestorage.app',
    iosBundleId: 'com.example.autoAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRSnmprUEUMFywSArFfHfB65dWzzAF1Ug',
    appId: '1:11209352050:web:879540b043ef19083973eb',
    messagingSenderId: '11209352050',
    projectId: 'auto-attendance-webapp',
    authDomain: 'auto-attendance-webapp.firebaseapp.com',
    storageBucket: 'auto-attendance-webapp.firebasestorage.app',
  );
}
